openapi: 3.0.0

info:
  description: "POC Swagger file for the new Service Versioning Definition."
  version: "1"
  title: "Service Versioning POC"
  contact:
    name: "Haroldo Macêdo"
    email: "haroldo.demacedo@nationwide.co.uk"
externalDocs:
  description: "Documentation"
  url: "http://swagger.io"

servers:
  - url: "https://{host}/si/"
    description: "Service to maintain the employees' information"
    variables:
      host:
        enum:
          - "api-desenv.nationwideintranet.co.uk"
          - "api-qa.nationwideintranet.co.uk"
          - "api.nationwideintranet.co.uk"
        default: "api-desenv.nationwideintranet.co.uk"
paths:
  /employees/:
    post:
      summary: "Include employee"
      operationId: "includeEmployee"
      requestBody:
        description: "Updated employee object"
        required: true
        content:
          application/nbs.nem.v1+json:
            schema:
              $ref: "#/components/schemas/Employee_v1"
      responses:
        '201':
          description: "New employee included"
        '400':
          description: "Invalid employee supplied"
        '404':
          description: "Employee not found"

  /employees/{employeeId}/:
    get:
      summary: "Get the employee from his internal ID"
      description: "Search the DB by the PK {employeeID}"
      operationId: "getEmployee"
      parameters:
        - name: employeeId
          in: path
          description: "Internal ID of the employee"
          required: true
          schema:
            type: integer
        - name: include
          in: query
          description: "Comma sepparated list of the returned relationships"
          schema:
            type: string
      responses:
        '200':
          description: "successful operation"
          content:
            application/nbs.nem.v1+json:
              schema:
                $ref: "#/components/schemas/Employee_v1"
        '400':
          description: "Invalid employee name supplied"
        '404':
          description: "Employee not found"
    delete:
      summary: "Delete employee"
      description: "This can only be done by the logged in user."
      operationId: "deleteEmployee"
      parameters:
        - name: employeeId
          in: path
          description: "The name that needs to be deleted"
          required: true
          schema:
            type: integer
      responses:
        400:
          description: "Invalid employeename supplied"
        404:
          description: "Employee not found"


components:
  schemas:
    Employee_v1:
      deprecated: true
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: "1234567890"
        fullname:
          type: "string"
          example: "John Doe"
        email:
          type: "string"
          format: email
          example: "contato@nationwide.co.uk"
        phone:
          type: "string"
          example: "01793-000000"
        status:
          type: "integer"
          format: "int32"
          description: "Employee Status"

